# Generated by Django 4.0.3 on 2022-04-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_muallif_ism_alter_student_ism'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muallif',
            name='kitoblar_soni',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
